### ISSUE TITLE
如何代理任意网站

### ISSUE THREAD

**Issue by yeshenshuijiao** [WincerChan/mirror#3]

**Comment by WincerChan** [comment]
https://github.com/WincerChan/mirror/blob/now_sh/config/index.go
改 33 行 和 34 行。

**Comment by yeshenshuijiao** [comment]
有些域名不行，比如rf.gd这些域名

**Comment by yeshenshuijiao** [comment]
不知道是什么原因，代理百度，谷歌是可以的，我搭了网站，qiaozhi1.rf.gd，想用zei反代加速国内访问，不行
